name: Build and Deploy Storybook

# Controls when the action will run. Triggers the workflow on push
# events where files change in the storybook-ui-components package
# but only for the master branch
on:
  push:
    branches: [ master ]
    paths: 
      - '/packages/storybook-ui-components/**'

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build-and-deploy-storybook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Authenticate on GCS
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd packages/storybook-ui-components/
    - run: npm run build
    
    - name: Deploy
      run: gsutil cp -r public/* gs://core-components.crdb.io
