name: Pull Request CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Lerna bootstrap
        run: lerna bootstrap

      - name: Build packages
        run: lerna run build

      - name: Continuous Integration for all packages
        run: lerna run ci --stream
        env:
          CI: true
